#ifndef __HTTP_RELATED_DEFINITIONS__
#define __HTTP_RELATED_DEFINITIONS__

enum HTTP_METHOD {GET, POST, HEAD, PUT, DELETE, TRACE, OPTIONS, CONNECT, PATCH};
enum HTTP_CODE {OK_200, BAD_REQUEST_400, FORBIDDEN_403, NOT_FOUND_404, INTERNAL_SERVER_ERROR_500};
enum HTTP_VERSION {HTTP_09, HTTP_10, HTTP_11, HTTP_20};

#endif