#ifndef __HTTP_RELATED_DEFINITIONS__
#define __HTTP_RELATED_DEFINITIONS__

enum HTTP_METHOD {GET, POST, HEAD, PUT, DELETE, TRACE, OPTIONS, CONNECT, PATCH};                    // HTTP请求方法
enum HTTP_CODE {OK_200, BAD_REQUEST_400, FORBIDDEN_403, NOT_FOUND_404, INTERNAL_SERVER_ERROR_500};  // HTTP状态码
enum HTTP_VERSION {HTTP_09, HTTP_10, HTTP_11, HTTP_20};                                             // HTTP版本

#endif